//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    
    public partial class p_s_uploadFiger_Result
    {
        public int workdayID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<System.DateTime> workday { get; set; }
        public Nullable<int> workmonth { get; set; }
        public Nullable<int> workyear { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string fullName { get; set; }
        public string wdName { get; set; }
        public string statusText { get; set; }
        public Nullable<System.TimeSpan> shift1_timeIn { get; set; }
        public Nullable<System.TimeSpan> shift1_timOut { get; set; }
        public Nullable<double> shift1_wd { get; set; }
        public Nullable<System.TimeSpan> shift2_timeIn { get; set; }
        public Nullable<System.TimeSpan> shift2_timOut { get; set; }
        public Nullable<double> shift2_wd { get; set; }
        public Nullable<System.TimeSpan> shift3_timeIn { get; set; }
        public Nullable<System.TimeSpan> shift3_timOut { get; set; }
        public Nullable<double> shift3_wd { get; set; }
        public Nullable<double> total_wd { get; set; }
        public Nullable<double> total_wh { get; set; }
        public Nullable<double> total_oth { get; set; }
        public string noted { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> GetDayW { get; set; }
        public Nullable<int> shiftstartDay { get; set; }
        public Nullable<int> shiftendDay { get; set; }
    }
}
