//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tasks
    {
        public int taskID { get; set; }
        public string taskName { get; set; }
        public string taskDetail { get; set; }
        public Nullable<int> emp_id { get; set; }
        public byte[] attachec_file { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<bool> status_com { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
