//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_dateSalaryLastMonth
    {
        public Nullable<int> reportGen { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> mgrID { get; set; }
        public Nullable<int> ownerID { get; set; }
        public System.DateTime generateDate { get; set; }
        public int salaryMonth { get; set; }
        public string fmenddate { get; set; }
        public string fmstartdate { get; set; }
        public int salaryID { get; set; }
    }
}
