//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_news
    {
        public int newsID { get; set; }
        public string newsTitle { get; set; }
        public string newsContrent { get; set; }
        public string attachec_file { get; set; }
        public Nullable<System.DateTime> pubish_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
