//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_rpt1012
    {
        public int tmpID { get; set; }
        public string transactionNo { get; set; }
        public string deptGroupCode { get; set; }
        public string deptGroupName { get; set; }
        public string descript { get; set; }
        public Nullable<int> headCount { get; set; }
        public Nullable<int> work_perma { get; set; }
        public Nullable<int> work_fixedTemp { get; set; }
        public Nullable<double> permaGrossincome { get; set; }
        public Nullable<double> fixedTempGrossincome { get; set; }
        public Nullable<double> grossBenefit { get; set; }
        public Nullable<double> bonus { get; set; }
        public Nullable<double> ovetime { get; set; }
        public Nullable<double> paidHours { get; set; }
        public Nullable<double> paidAbsent { get; set; }
        public Nullable<int> AL { get; set; }
        public Nullable<int> sick { get; set; }
        public Nullable<int> CL { get; set; }
        public Nullable<int> publicHoliday { get; set; }
        public Nullable<double> unpaidLeave { get; set; }
        public Nullable<int> OT150 { get; set; }
        public Nullable<int> OT200 { get; set; }
        public Nullable<int> OT250 { get; set; }
        public Nullable<int> OT300 { get; set; }
        public Nullable<int> OT350 { get; set; }
        public Nullable<int> headcount_perma { get; set; }
        public Nullable<int> headcount_temp { get; set; }
        public Nullable<double> wh_paid { get; set; }
        public Nullable<double> wh_absent { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> yearCal { get; set; }
        public Nullable<int> userID { get; set; }
    }
}
