//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_EmployeeDetailsWorkStatus_1
    {
        public int emp_id { get; set; }
        public Nullable<int> titleid { get; set; }
        public Nullable<int> etid { get; set; }
        public Nullable<int> natid { get; set; }
        public Nullable<int> relid { get; set; }
        public Nullable<int> wtsid { get; set; }
        public Nullable<int> wuid { get; set; }
        public Nullable<int> esid { get; set; }
        public string intypeid { get; set; }
        public string Emp_nbr { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string F_name_l1 { get; set; }
        public string Surname_L1 { get; set; }
        public string F_name_l2 { get; set; }
        public string Surname_L2 { get; set; }
        public string TitleName { get; set; }
        public string Departname { get; set; }
        public string Ethnic { get; set; }
        public string NationName { get; set; }
        public string Languages { get; set; }
        public string Religion { get; set; }
        public string WorkStatus { get; set; }
        public string WorkHours { get; set; }
        public string Unitname { get; set; }
        public string insurance { get; set; }
        public string Inpercent { get; set; }
        public string ComPercent { get; set; }
        public string MaxMoney { get; set; }
        public System.DateTime Emp_DOB { get; set; }
        public string emp_phone1 { get; set; }
        public string emp_phone2 { get; set; }
        public string emp_fbook { get; set; }
        public string emp_idcard { get; set; }
        public string emp_photo { get; set; }
        public string consult { get; set; }
        public string Passportno { get; set; }
        public string groupblood { get; set; }
        public string heigh { get; set; }
        public string empWeight { get; set; }
        public string standardTax { get; set; }
        public Nullable<int> mgrid { get; set; }
        public string suppervisor { get; set; }
        public string empBorn { get; set; }
        public string Nickname { get; set; }
        public string emp_office { get; set; }
        public string Cal_payroll { get; set; }
        public string User_email { get; set; }
        public int CMID { get; set; }
        public string CMName { get; set; }
        public int DEPID { get; set; }
        public string intypenumber { get; set; }
        public string IDcard { get; set; }
        public System.DateTime Emp_startdate { get; set; }
        public Nullable<int> Genid { get; set; }
        public string Emp_enddate { get; set; }
        public double percentSalary { get; set; }
        public string dateworking { get; set; }
        public Nullable<int> numYear { get; set; }
        public Nullable<int> numMonth { get; set; }
        public string MgrTitle { get; set; }
        public string mgrFirstName1 { get; set; }
        public string mgrlastName1 { get; set; }
        public string mgrFirstName2 { get; set; }
        public string mgrLastName2 { get; set; }
        public string mgrPosition { get; set; }
    }
}
