//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pr_approve
    {
        public int approveGroupID { get; set; }
        public Nullable<int> GLUID { get; set; }
        public Nullable<int> approceLevel { get; set; }
        public Nullable<int> managerOrPerson { get; set; }
        public Nullable<int> personId { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> user_add { get; set; }
    }
}
