//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_emp_question
    {
        public int empQuestionID { get; set; }
        public Nullable<int> empId { get; set; }
        public string QName { get; set; }
        public Nullable<double> MaxScores { get; set; }
        public Nullable<int> evaluate_1_status { get; set; }
        public Nullable<double> scrore_1 { get; set; }
        public Nullable<int> evaluate_2_status { get; set; }
        public Nullable<double> scrore_2 { get; set; }
        public Nullable<int> evaluate_3_status { get; set; }
        public Nullable<double> scrore_3 { get; set; }
        public Nullable<int> evaluate_4_status { get; set; }
        public Nullable<double> scrore_4 { get; set; }
        public Nullable<int> status_id { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
