//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_myRequest
    {
        public int leaveRequestID { get; set; }
        public string leaveRequestNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string requestType { get; set; }
        public Nullable<int> leaveTypeID { get; set; }
        public string leaveTypeCode { get; set; }
        public string leaveTypeName1 { get; set; }
        public string leaveTypeName2 { get; set; }
        public string leaveDay { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<int> amountDay { get; set; }
        public string noted { get; set; }
        public string mgrempTitleName { get; set; }
        public string mgrfirstName1 { get; set; }
        public string mgrlastName1 { get; set; }
        public string mgrfirstName2 { get; set; }
        public string mgrlastName2 { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<int> delegateEmpID { get; set; }
        public string respempTitleName { get; set; }
        public string respfirstName1 { get; set; }
        public string resplastName1 { get; set; }
        public string respfirstName2 { get; set; }
        public string resplastName2 { get; set; }
        public string fileAttached { get; set; }
        public Nullable<int> status_ID { get; set; }
        public string status_text { get; set; }
        public Nullable<int> user_add { get; set; }
        public string userAddempTitleName { get; set; }
        public string userAddfirstName1 { get; set; }
        public string userAddlastName1 { get; set; }
        public string userAddfirstName2 { get; set; }
        public string userAddlastName2 { get; set; }
        public string empTitleName { get; set; }
        public string firstName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string lastName1 { get; set; }
    }
}
