//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bonus_summary
    {
        public int bonusAccureID { get; set; }
        public Nullable<int> empID { get; set; }
        public string sec { get; set; }
        public string groupName { get; set; }
        public Nullable<int> bonusMonth { get; set; }
        public Nullable<int> bonusYear { get; set; }
        public Nullable<System.DateTime> YTD { get; set; }
        public Nullable<double> basicSalary { get; set; }
        public Nullable<double> LTL_LengthOfService { get; set; }
        public Nullable<double> bonus_LTL { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
