//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_listquestionempdetails
    {
        public int LQDID { get; set; }
        public Nullable<int> QTLID { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public string questionName { get; set; }
        public Nullable<int> masterScore { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<double> managerscore { get; set; }
        public Nullable<double> managerscore2 { get; set; }
        public Nullable<double> managerscore3 { get; set; }
        public Nullable<double> hrscore { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> inputhr { get; set; }
        public Nullable<System.DateTime> ownercreate { get; set; }
        public Nullable<System.DateTime> managercreate { get; set; }
        public Nullable<System.DateTime> hrcreatedate { get; set; }
        public Nullable<bool> ownerinfo { get; set; }
        public Nullable<bool> mgrkey { get; set; }
        public Nullable<bool> hrkey { get; set; }
        public string rec_type_emp { get; set; }
        public string rec_type_mgr { get; set; }
        public string rec_type_hr { get; set; }
        public string employeemoreinfo { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> directorapprove { get; set; }
        public string rec_type_directory { get; set; }
        public Nullable<int> directorscore { get; set; }
        public Nullable<bool> mgrfinishedquestion { get; set; }
        public Nullable<int> hr_join { get; set; }
        public Nullable<double> sumaryScoreHr { get; set; }
        public string commentsbyemp { get; set; }
        public string commentsbymanager { get; set; }
        public Nullable<int> ownerReview { get; set; }
        public Nullable<int> mgrReview { get; set; }
        public Nullable<int> hrReview { get; set; }
        public Nullable<int> viceReview { get; set; }
        public Nullable<int> presidentReview { get; set; }
        public Nullable<int> completeTask { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
