//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_reportperformancereview
    {
        public int RPID { get; set; }
        public Nullable<double> countkpi { get; set; }
        public Nullable<double> countkbi { get; set; }
        public Nullable<double> scorekpi { get; set; }
        public Nullable<double> scorekbi { get; set; }
        public Nullable<double> totalkpi { get; set; }
        public Nullable<double> totalkbi { get; set; }
        public Nullable<double> totalkpi_kbi { get; set; }
        public string kpiame { get; set; }
        public string kbiname { get; set; }
        public Nullable<int> managerid { get; set; }
        public Nullable<int> directorid { get; set; }
        public Nullable<int> hrid { get; set; }
        public string empComments { get; set; }
        public string mgrComments { get; set; }
        public string directorComments { get; set; }
        public string hrComments { get; set; }
        public string managername { get; set; }
        public string directorname { get; set; }
        public string hrname { get; set; }
        public string sessionclick { get; set; }
        public string mgr_empComments { get; set; }
    }
}
