//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_severance
    {
        public int severanceID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empWorkDayID { get; set; }
        public string deptCode { get; set; }
        public string sec { get; set; }
        public string gender { get; set; }
        public Nullable<double> basicSalrary { get; set; }
        public Nullable<int> severanceMonth { get; set; }
        public Nullable<int> severanceYear { get; set; }
        public Nullable<System.DateTime> severanceDate { get; set; }
        public Nullable<System.DateTime> ltcHireDate { get; set; }
        public Nullable<System.DateTime> ltlHireDate { get; set; }
        public Nullable<double> lengthService { get; set; }
        public Nullable<double> severanceAmount { get; set; }
        public string remark { get; set; }
        public Nullable<int> typeID { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
