//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_otRequestDetail
    {
        public int otRequestDetailID { get; set; }
        public int otRequestID { get; set; }
        public int otSettingID { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public double qtyHour { get; set; }
    
        public virtual tb_ot_setting tb_ot_setting { get; set; }
        public virtual tb_otRequest tb_otRequest { get; set; }
    }
}
