//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_p_headerquestion_1
    {
        public int HDQID { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<double> kpi_percent { get; set; }
        public Nullable<double> kbi_percent { get; set; }
        public Nullable<int> GLUID { get; set; }
        public Nullable<int> mgr1_id { get; set; }
    }
}
