//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empBankAccount
    {
        public int empBankAccountID { get; set; }
        public int bankID { get; set; }
        public int empID { get; set; }
        public string bankAccountName { get; set; }
        public string bankAccountNo { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_bank tb_bank { get; set; }
        public virtual tb_employees tb_employees { get; set; }
    }
}
