//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    
    public partial class pd_sumcheckleaveall_Result
    {
        public Nullable<int> leaveTypeID { get; set; }
        public Nullable<int> transactionType { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> yearm { get; set; }
        public Nullable<double> total { get; set; }
    }
}
