//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_mobile_paymentrecord
    {
        public int salaryid { get; set; }
        public Nullable<System.DateTime> strdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> monthcal { get; set; }
        public Nullable<int> monthyear { get; set; }
    }
}
