//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_loan
    {
        public int loanID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<double> amountLoan { get; set; }
        public Nullable<int> loanMonth { get; set; }
        public Nullable<double> loanPercent { get; set; }
        public Nullable<System.DateTime> loanStart { get; set; }
        public Nullable<System.DateTime> loanEnd { get; set; }
        public string LoanReason { get; set; }
        public Nullable<System.DateTime> monthBL { get; set; }
        public Nullable<double> acc_balance { get; set; }
        public Nullable<double> monthlyPay { get; set; }
        public Nullable<double> loan_incen { get; set; }
        public Nullable<double> pay_amount { get; set; }
        public Nullable<int> paidStatus { get; set; }
        public Nullable<System.DateTime> payDate { get; set; }
        public Nullable<int> status_id { get; set; }
        public int loanDetailID { get; set; }
        public Nullable<int> payLoadStatus { get; set; }
    }
}
