//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_headerquestionemployeecomments
    {
        public int HECID { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string textcomments { get; set; }
        public Nullable<System.DateTime> commentdate { get; set; }
        public string Emp_nbr { get; set; }
        public string User_email { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string TitleName { get; set; }
        public string Departname { get; set; }
        public string CMName { get; set; }
        public string Unitname { get; set; }
        public string WorkStatus { get; set; }
        public Nullable<int> commentby { get; set; }
        public string manageremp_nbr { get; set; }
        public string managerlaoname { get; set; }
        public string managerenglishname { get; set; }
        public string RecType { get; set; }
        public Nullable<int> RecjectTo { get; set; }
    }
}
