//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_evaluate_header_3
    {
        public int HDQID { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> headerYear { get; set; }
        public Nullable<int> hrId { get; set; }
        public Nullable<int> ownerscore_StatusId { get; set; }
        public Nullable<int> managerscore1_statusId { get; set; }
        public Nullable<int> managerscore2_statusId { get; set; }
        public Nullable<int> managerscore3_statusId { get; set; }
        public Nullable<int> hrscore_statusid { get; set; }
    }
}
