//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_questionpart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_p_questionpart()
        {
            this.tb_evaluate_emp = new HashSet<tb_evaluate_emp>();
        }
    
        public int QTID { get; set; }
        public Nullable<int> TQID { get; set; }
        public Nullable<int> QuestoinpartNo { get; set; }
        public string Questionpartname { get; set; }
        public string rec_type { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<int> hdqid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_evaluate_emp> tb_evaluate_emp { get; set; }
    }
}
