//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    
    public partial class p_Payslip1_Result
    {
        public int SalaryID { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empTitleName { get; set; }
        public string empEmail { get; set; }
        public string firstname1 { get; set; }
        public string lastname1 { get; set; }
        public string firstname2 { get; set; }
        public string lastname2 { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string unitName1 { get; set; }
        public string unitname2 { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> yearCal { get; set; }
        public string empworkingDay { get; set; }
        public string empPosition { get; set; }
        public string empTypeText { get; set; }
        public double basicSalary { get; set; }
        public string strDate { get; set; }
        public string endDate { get; set; }
        public Nullable<System.DateTime> nStrDate { get; set; }
        public Nullable<System.DateTime> nEnddate { get; set; }
        public int deptID { get; set; }
        public Nullable<int> workingmonth { get; set; }
        public string costCenterCode { get; set; }
        public string costcentertext { get; set; }
        public string shiftincomeA { get; set; }
        public string shiftincomeB { get; set; }
        public string shiftincomeC { get; set; }
        public string TotalShiftIncome { get; set; }
        public Nullable<int> OT1 { get; set; }
        public Nullable<int> OT2 { get; set; }
        public Nullable<int> OT3 { get; set; }
        public Nullable<int> OT4 { get; set; }
        public Nullable<int> OT5 { get; set; }
        public Nullable<int> SumOT { get; set; }
        public string overtimeincome1 { get; set; }
        public string overtimeincome2 { get; set; }
        public string overtimeincome3 { get; set; }
        public string overtimeincome4 { get; set; }
        public string overtimeincome5 { get; set; }
        public string Totalovertimeincome { get; set; }
        public string leavedays { get; set; }
        public string qyears { get; set; }
        public Nullable<double> sickleavedays { get; set; }
        public string allowance_phone { get; set; }
        public string allowance_fuel { get; set; }
        public string allowance_housing { get; set; }
        public string allowance_car { get; set; }
        public string totalAllowance { get; set; }
        public string TotalTaxpaid { get; set; }
        public string EmployeeSSO { get; set; }
        public string deductFHF { get; set; }
        public string SLDRTFund { get; set; }
        public string severanceBook { get; set; }
        public string grossVariance { get; set; }
        public string Advancebonus { get; set; }
        public string OtherAllowance { get; set; }
        public string NetToPay { get; set; }
        public string NetIncome { get; set; }
        public Nullable<double> annualeavetotal { get; set; }
        public Nullable<double> annualeaveused { get; set; }
        public Nullable<double> annualeavebalance { get; set; }
        public Nullable<double> ComposulyLeave { get; set; }
        public string empDayID { get; set; }
        public string empType { get; set; }
    }
}
