//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_app_role_permission
    {
        public int appId { get; set; }
        public Nullable<int> roleId { get; set; }
        public Nullable<int> app_permissionId { get; set; }
        public Nullable<int> app_view { get; set; }
        public Nullable<int> app_add { get; set; }
        public Nullable<int> app_edit { get; set; }
        public Nullable<int> app_del { get; set; }
        public Nullable<int> app_action { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_app_permission tb_app_permission { get; set; }
        public virtual tb_app_role tb_app_role { get; set; }
    }
}
