//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_summary_bonus
    {
        public int adv_bonusID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empWorkDayID { get; set; }
        public string deptCode { get; set; }
        public string sec { get; set; }
        public double bonusAmount_00 { get; set; }
        public double bonusAmount_01 { get; set; }
        public double bonusAmount_02 { get; set; }
        public double bonusAmount_03 { get; set; }
        public double bonusAmount_04 { get; set; }
        public double bonusAmount_05 { get; set; }
        public double bonusAmount_06 { get; set; }
        public double bonusAmount_07 { get; set; }
        public double bonusAmount_08 { get; set; }
        public double bonusAmount_09 { get; set; }
        public double bonusAmount_10 { get; set; }
        public double bonusAmount_11 { get; set; }
        public double bonusAmount_12 { get; set; }
        public Nullable<int> cal { get; set; }
    }
}
