//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    
    public partial class p_InsertLeaveRequest_BAK_Result
    {
        public Nullable<int> exc { get; set; }
        public Nullable<int> checkx { get; set; }
    }
}
