//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_evaluate
    {
        public int logid { get; set; }
        public Nullable<System.DateTime> logDate { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> empQuestionID { get; set; }
        public string evaluate_name { get; set; }
        public Nullable<double> scrore { get; set; }
        public string confirmEveluate { get; set; }
    }
}
