//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_otRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_otRequest()
        {
            this.tb_otApprove = new HashSet<tb_otApprove>();
            this.tb_otRequestDetail = new HashSet<tb_otRequestDetail>();
        }
    
        public int otRequestID { get; set; }
        public string otRequestNo { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> otTypeID { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public System.TimeSpan otStartTime { get; set; }
        public System.TimeSpan otEndTime { get; set; }
        public string noted { get; set; }
        public string fileAttached { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_otApprove> tb_otApprove { get; set; }
        public virtual tb_status tb_status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_otRequestDetail> tb_otRequestDetail { get; set; }
    }
}
