//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_view_upload
    {
        public int tmpId { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string fullName { get; set; }
        public string costCenter { get; set; }
        public Nullable<double> sh1 { get; set; }
        public Nullable<double> sh2 { get; set; }
        public Nullable<double> sh3 { get; set; }
        public Nullable<double> total_wd { get; set; }
        public Nullable<double> total_wm { get; set; }
        public string remark { get; set; }
        public Nullable<double> al { get; set; }
        public Nullable<double> sl { get; set; }
        public Nullable<double> cl { get; set; }
        public Nullable<double> dil { get; set; }
        public Nullable<double> ml { get; set; }
        public Nullable<double> pl { get; set; }
        public Nullable<double> otherl { get; set; }
        public Nullable<double> lwp { get; set; }
        public Nullable<double> publicHoliday { get; set; }
        public Nullable<double> wh { get; set; }
        public Nullable<double> wf { get; set; }
        public Nullable<double> dayOff { get; set; }
    }
}
