//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_additionalDeduction
    {
        public int addDeducID { get; set; }
        public string transactionNo { get; set; }
        public string addDeducName { get; set; }
        public Nullable<int> deductMonth { get; set; }
        public Nullable<int> deductYear { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> addDeducMonth { get; set; }
        public Nullable<double> totaladdDeduc { get; set; }
        public string noted { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string statusText { get; set; }
    }
}
