//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empOT_request
    {
        public int otRequestID { get; set; }
        public string otRequestNo { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> otTypeID { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public System.TimeSpan otStartTime { get; set; }
        public System.TimeSpan otEndTime { get; set; }
        public int otRequestDetailID { get; set; }
        public int otSettingID { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public double qtyHour { get; set; }
    }
}
