//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_viewSumLeave
    {
        public int viewID { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string fullName1 { get; set; }
        public string fullName2 { get; set; }
        public string empPosition { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public Nullable<int> totalDay1 { get; set; }
        public Nullable<int> totalDay2 { get; set; }
        public Nullable<int> totalDay3 { get; set; }
        public Nullable<int> totalDay4 { get; set; }
        public Nullable<int> user_view { get; set; }
        public Nullable<System.DateTime> date_view { get; set; }
        public string ip_view { get; set; }
        public string transactionView { get; set; }
    }
}
