//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_listquestionbyemployee
    {
        public int LQDID { get; set; }
        public Nullable<int> QTLID { get; set; }
        public int QTID { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> Qno { get; set; }
        public string QName { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<System.DateTime> ownercreate { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public string Emp_nbr { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string User_email { get; set; }
        public string CMName { get; set; }
        public string Unitname { get; set; }
        public string Departname { get; set; }
        public string TitleName { get; set; }
        public string rec_type_emp { get; set; }
        public string rec_type_mgr { get; set; }
        public string rec_type_hr { get; set; }
        public Nullable<int> partNumber { get; set; }
        public string partQuestionName { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<bool> mgrfinishedquestion { get; set; }
    }
}
