//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_approvalSetting
    {
        public int approveID { get; set; }
        public Nullable<int> appLevel { get; set; }
        public Nullable<int> approveTypeID { get; set; }
        public Nullable<int> approveDept { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_appType tb_appType { get; set; }
        public virtual tb_department tb_department { get; set; }
        public virtual tb_employees tb_employees { get; set; }
    }
}
