//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_fingerCheck
    {
        public int empID { get; set; }
        public string empNo { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public Nullable<double> shift1_wd { get; set; }
        public Nullable<double> shift2_wd { get; set; }
        public Nullable<double> shift3_wd { get; set; }
        public Nullable<double> total_wd { get; set; }
        public Nullable<double> total_oth { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> status_id { get; set; }
        public string status_text { get; set; }
        public Nullable<double> shift2_wd_sun { get; set; }
        public Nullable<double> hift2_oth_sun { get; set; }
    }
}
