//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_P_GroupLevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_P_GroupLevels()
        {
            this.tbl_P_employeeLevel_GroupLevels = new HashSet<tbl_P_employeeLevel_GroupLevels>();
            this.tbl_P_employeeLevel_GroupLevels1 = new HashSet<tbl_P_employeeLevel_GroupLevels>();
            this.tbl_P_employeeLevel_GroupLevels2 = new HashSet<tbl_P_employeeLevel_GroupLevels>();
            this.tbl_p_grouppermission = new HashSet<tbl_p_grouppermission>();
            this.tbl_p_grouppermission1 = new HashSet<tbl_p_grouppermission>();
            this.tbl_p_HeaderquestionGrouplevel = new HashSet<tbl_p_HeaderquestionGrouplevel>();
        }
    
        public int GLUID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupLevels { get; set; }
        public string moreinfo { get; set; }
        public Nullable<int> Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Rec_type { get; set; }
        public Nullable<int> approveby { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_P_employeeLevel_GroupLevels> tbl_P_employeeLevel_GroupLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_P_employeeLevel_GroupLevels> tbl_P_employeeLevel_GroupLevels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_P_employeeLevel_GroupLevels> tbl_P_employeeLevel_GroupLevels2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_p_grouppermission> tbl_p_grouppermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_p_grouppermission> tbl_p_grouppermission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_p_HeaderquestionGrouplevel> tbl_p_HeaderquestionGrouplevel { get; set; }
    }
}
