//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empleaverequestallbymgrid
    {
        public int salaryid { get; set; }
        public string transactionno { get; set; }
        public Nullable<int> orderno { get; set; }
        public Nullable<int> monthcal { get; set; }
        public Nullable<int> yearcal { get; set; }
        public Nullable<System.DateTime> mycal { get; set; }
        public string deptgroupcode { get; set; }
        public string deptgroupname { get; set; }
        public string costcentercode { get; set; }
        public string costcentertext { get; set; }
        public string deptcode { get; set; }
        public string deptname1 { get; set; }
        public string deptname2 { get; set; }
        public string unitcode { get; set; }
        public string unitname1 { get; set; }
        public string unitname2 { get; set; }
        public Nullable<int> empid { get; set; }
        public string empno { get; set; }
        public string empdayid { get; set; }
        public string empname1 { get; set; }
        public string empname2 { get; set; }
        public string emptype { get; set; }
        public double oldsalary { get; set; }
        public double incrementsalary { get; set; }
        public Nullable<int> setworkingday { get; set; }
        public Nullable<int> empworkingday { get; set; }
        public Nullable<double> shiftwd1 { get; set; }
        public Nullable<double> shiftwd2 { get; set; }
        public Nullable<double> shiftwd3 { get; set; }
        public Nullable<double> otshift1 { get; set; }
        public Nullable<double> otshift2 { get; set; }
        public Nullable<double> otshift3 { get; set; }
        public Nullable<double> otrate1 { get; set; }
        public Nullable<double> otrate2 { get; set; }
        public Nullable<double> otrate3 { get; set; }
        public Nullable<double> otrate4 { get; set; }
        public Nullable<double> otrate5 { get; set; }
        public Nullable<double> sumot { get; set; }
        public Nullable<int> publicholiday { get; set; }
        public Nullable<System.DateTime> strdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string fstartdate { get; set; }
        public string fenddate { get; set; }
        public string yearmonths { get; set; }
        public Nullable<int> leaveday { get; set; }
        public Nullable<int> empdayoff { get; set; }
        public double basicsalary { get; set; }
        public double shiftincome1 { get; set; }
        public double shiftincome2 { get; set; }
        public double shiftincome3 { get; set; }
        public double shiftincome { get; set; }
        public double overtimeincome1 { get; set; }
        public double overtimeincome2 { get; set; }
        public double overtimeincome3 { get; set; }
        public double overtimeincome4 { get; set; }
        public double overtimeincome5 { get; set; }
        public double overtimeincome { get; set; }
        public double threshingincom { get; set; }
        public double additionalpay { get; set; }
        public double additionalDeduct { get; set; }
        public double deductdayoff { get; set; }
        public double allowance_phone { get; set; }
        public double allowance_fuel { get; set; }
        public double allowance_housing { get; set; }
        public double allowance_car { get; set; }
        public double allowance { get; set; }
        public double grosssalarybenefits { get; set; }
        public double saleincentive { get; set; }
        public double paybonus { get; set; }
        public double advancebonus { get; set; }
        public double grossincome { get; set; }
        public double deductempsso { get; set; }
        public double tax_b1 { get; set; }
        public double tax_b2 { get; set; }
        public double tax_b3 { get; set; }
        public double tax_b4 { get; set; }
        public double tax_b5 { get; set; }
        public double tax_b6 { get; set; }
        public double tax_extra { get; set; }
        public double deducttaxs { get; set; }
        public double netincome { get; set; }
        public double deductloan { get; set; }
        public double deductfhf { get; set; }
        public double deduct_sldrt_fun { get; set; }
        public double deductother { get; set; }
        public double canteenNet { get; set; }
        public double otherallowanNet { get; set; }
        public double severanceBook { get; set; }
        public double nettopay { get; set; }
        public double employersso { get; set; }
        public double grossLastmonth { get; set; }
        public double grossvariance { get; set; }
        public string noted { get; set; }
        public Nullable<int> approve_id { get; set; }
        public string bankname { get; set; }
        public string bankaccountname { get; set; }
        public string bankaccountNo { get; set; }
        public Nullable<int> al { get; set; }
        public string al_use { get; set; }
        public string al_left { get; set; }
        public Nullable<int> sick { get; set; }
        public Nullable<int> cl { get; set; }
        public string ssonumber { get; set; }
        public string workdayid { get; set; }
        public Nullable<int> mgrid { get; set; }
    }
}
