//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_grouppermissionLoginbyLevels
    {
        public int GPPLLID { get; set; }
        public Nullable<int> PMSID { get; set; }
        public Nullable<int> GroupLevels { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string Rec_type { get; set; }
    }
}
