//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employeeleave_thisyear
    {
        public Nullable<int> leaveTypeID { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string laoname { get; set; }
        public string engname { get; set; }
        public string leavetype { get; set; }
        public Nullable<double> amountday { get; set; }
        public string expdate { get; set; }
    }
}
