//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_adv_bonus
    {
        public int adv_bonusID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empWorkDayID { get; set; }
        public string deptCode { get; set; }
        public string sec { get; set; }
        public string gender { get; set; }
        public Nullable<double> basicSalrary { get; set; }
        public Nullable<int> bonusMonth { get; set; }
        public Nullable<int> bounusYear { get; set; }
        public Nullable<System.DateTime> ltcHireDate { get; set; }
        public Nullable<System.DateTime> ltlHireDate { get; set; }
        public Nullable<System.DateTime> bonusStrDate { get; set; }
        public Nullable<System.DateTime> bonusDate { get; set; }
        public string bonusEndDate { get; set; }
        public Nullable<int> numMonthBonus { get; set; }
        public Nullable<decimal> lengthService { get; set; }
        public Nullable<double> bonusAmount { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> typeID { get; set; }
    }
}
