//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_delagate
    {
        public int delegateID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> delegateEmpID { get; set; }
        public string noted { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> reCallDate { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string delegateNote { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
        public virtual tb_status tb_status { get; set; }
    }
}
