//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empEducation
    {
        public int empEducationID { get; set; }
        public int empID { get; set; }
        public int educationTypeID { get; set; }
        public string educationLevelText { get; set; }
        public string schoolName { get; set; }
        public string levelReceive { get; set; }
        public string acdamyYear { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_educationType tb_educationType { get; set; }
        public virtual tb_employees tb_employees { get; set; }
    }
}
