//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empSSO
    {
        public int empSSOID { get; set; }
        public Nullable<int> empID { get; set; }
        public int ssoID { get; set; }
        public Nullable<double> SSOValue { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public string remark { get; set; }
        public string ssoNumber { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
        public virtual tb_sso tb_sso { get; set; }
    }
}
