//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empInfo
    {
        public int empInfoID { get; set; }
        public Nullable<int> positionID { get; set; }
        public string empPosition { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> empLevelID { get; set; }
        public Nullable<System.DateTime> ltcHireDate { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public Nullable<int> empGroupID { get; set; }
        public Nullable<int> shiftWorkingID { get; set; }
        public Nullable<int> costCenterID { get; set; }
        public string assignmentLocation { get; set; }
        public string currentAddress { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> workingStatusID { get; set; }
        public Nullable<int> empTypeID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<System.DateTime> actingDate { get; set; }
        public Nullable<int> ssoExpert { get; set; }
    
        public virtual tb_costCenter tb_costCenter { get; set; }
        public virtual tb_empGroup tb_empGroup { get; set; }
        public virtual tb_empLevel tb_empLevel { get; set; }
        public virtual tb_employees tb_employees { get; set; }
        public virtual tb_TaxType tb_TaxType { get; set; }
        public virtual tb_unit tb_unit { get; set; }
    }
}
