//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_evaluate_emp
    {
        public int questionId { get; set; }
        public Nullable<int> HDQID { get; set; }
        public Nullable<int> QTID { get; set; }
        public Nullable<int> questionNumber { get; set; }
        public Nullable<int> empId { get; set; }
        public string questionName { get; set; }
        public Nullable<int> masterScore { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<int> ownerscore_StatusId { get; set; }
        public Nullable<System.DateTime> ownercreate { get; set; }
        public Nullable<int> mgr1_id { get; set; }
        public Nullable<double> managerscore1 { get; set; }
        public Nullable<int> managerscore1_statusId { get; set; }
        public Nullable<System.DateTime> manager1_create { get; set; }
        public Nullable<int> mgr2_id { get; set; }
        public Nullable<double> managerscore2 { get; set; }
        public Nullable<int> managerscore2_statusId { get; set; }
        public Nullable<System.DateTime> manager2_create { get; set; }
        public Nullable<int> mgr3_id { get; set; }
        public Nullable<double> managerscore3 { get; set; }
        public Nullable<int> managerscore3_statusId { get; set; }
        public Nullable<System.DateTime> manager3_create { get; set; }
        public Nullable<int> hrId { get; set; }
        public Nullable<double> hrscore { get; set; }
        public Nullable<int> hrscore_statusid { get; set; }
        public Nullable<System.DateTime> hr_create { get; set; }
        public string ownerComment { get; set; }
        public string managerscore1_Comment { get; set; }
        public string managerscore2_Comment { get; set; }
        public string managerscore3_Comment { get; set; }
        public string hrscore_Comment { get; set; }
        public Nullable<int> mgr1_increanPercent { get; set; }
        public Nullable<int> mgr1_increanLevel { get; set; }
        public Nullable<int> mgr1_increanPosition { get; set; }
        public string mgr1_comment { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> ps { get; set; }
    
        public virtual tbl_p_questionpart tbl_p_questionpart { get; set; }
        public virtual tbl_p_headerquestion tbl_p_headerquestion { get; set; }
    }
}
