//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_getHistoryLeave
    {
        public int HLID { get; set; }
        public string leaverequestno { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<int> leavetypeid { get; set; }
        public Nullable<double> amountday { get; set; }
        public Nullable<int> saveby { get; set; }
        public string inputStatus { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
