//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_paymentRecord
    {
        public int salaryID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> orderNo { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> YearCal { get; set; }
        public Nullable<System.DateTime> MYCal { get; set; }
        public string deptGroupCode { get; set; }
        public string deptGroupName { get; set; }
        public Nullable<int> costCenterNo { get; set; }
        public string costCenterCode { get; set; }
        public string costCenterText { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string unitCode { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empDayID { get; set; }
        public string empName1 { get; set; }
        public string empName2 { get; set; }
        public string empType { get; set; }
        public double oldSalary { get; set; }
        public double incrementSalary { get; set; }
        public Nullable<double> SetWorkingDay { get; set; }
        public Nullable<double> EmpWorkingDay { get; set; }
        public Nullable<double> shiftWD1 { get; set; }
        public Nullable<double> shiftWD2 { get; set; }
        public Nullable<double> shiftWD3 { get; set; }
        public Nullable<double> otshift1 { get; set; }
        public Nullable<double> otshift2 { get; set; }
        public Nullable<double> otshift3 { get; set; }
        public Nullable<double> OTRate1 { get; set; }
        public Nullable<double> OTRate2 { get; set; }
        public Nullable<double> OTRate3 { get; set; }
        public Nullable<double> OTRate4 { get; set; }
        public Nullable<double> OTRate5 { get; set; }
        public Nullable<double> sumOT { get; set; }
        public Nullable<double> publicHoliday { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<double> leaveDay { get; set; }
        public Nullable<double> EmpDayOff { get; set; }
        public double basicSalary { get; set; }
        public double shiftIncome1 { get; set; }
        public double shiftIncome2 { get; set; }
        public double shiftIncome3 { get; set; }
        public double shiftIncome { get; set; }
        public double overtimeIncome1 { get; set; }
        public double overtimeIncome2 { get; set; }
        public double overtimeIncome3 { get; set; }
        public double overtimeIncome4 { get; set; }
        public double overtimeIncome5 { get; set; }
        public double overtimeIncome { get; set; }
        public double threshingIncom { get; set; }
        public double additionalPay { get; set; }
        public double additionalDeduct { get; set; }
        public double deductDayOff { get; set; }
        public double allowance_phone { get; set; }
        public double allowance_fuel { get; set; }
        public double allowance_housing { get; set; }
        public double allowance_car { get; set; }
        public double allowance { get; set; }
        public double grossSalaryBenefits { get; set; }
        public double saleIncentive { get; set; }
        public double payBonus { get; set; }
        public double advanceBonus { get; set; }
        public double grossIncome { get; set; }
        public double deductEmpSSO { get; set; }
        public double tax_b1 { get; set; }
        public double tax_b2 { get; set; }
        public double tax_b3 { get; set; }
        public double tax_b4 { get; set; }
        public double tax_b5 { get; set; }
        public double tax_b6 { get; set; }
        public double tax_extra { get; set; }
        public double deductTaxs { get; set; }
        public double netIncome { get; set; }
        public double deductLoan { get; set; }
        public double deductFHF { get; set; }
        public double deduct_SLDRT_fun { get; set; }
        public double deductOther { get; set; }
        public double canteenNET { get; set; }
        public double OtherAllowanNET { get; set; }
        public double severanceBook { get; set; }
        public double NetToPay { get; set; }
        public double employerSSO { get; set; }
        public double grossLastMonth { get; set; }
        public double grossVariance { get; set; }
        public string noted { get; set; }
        public Nullable<int> approve_id { get; set; }
        public string bankName { get; set; }
        public string bankAccountName { get; set; }
        public string bankAccountNo { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_id { get; set; }
        public string statusText { get; set; }
        public string staffName { get; set; }
        public Nullable<int> monthCycle { get; set; }
        public Nullable<int> LoanDetailID { get; set; }
        public Nullable<int> SLDRT_funDetailID { get; set; }
        public Nullable<double> al { get; set; }
        public Nullable<double> al_use { get; set; }
        public Nullable<double> al_left { get; set; }
        public Nullable<double> sick { get; set; }
        public Nullable<double> cl { get; set; }
        public string ssoNumber { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public Nullable<System.DateTime> hireDayLTL { get; set; }
        public Nullable<double> workprevious { get; set; }
        public Nullable<int> ssoExpert { get; set; }
        public string workdayID { get; set; }
        public string groupCostCenterCode { get; set; }
        public string groupCostCenterText { get; set; }
        public Nullable<double> wfh { get; set; }
        public Nullable<double> wff { get; set; }
        public Nullable<double> countSL { get; set; }
        public Nullable<double> countAL { get; set; }
        public Nullable<double> countCL { get; set; }
        public Nullable<double> countDIL { get; set; }
        public Nullable<double> countML { get; set; }
        public Nullable<double> countPL { get; set; }
        public Nullable<double> countOther { get; set; }
        public Nullable<double> countLWP { get; set; }
        public Nullable<double> countPublicHoliday { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
        public virtual tb_paymentRecord tb_paymentRecord1 { get; set; }
        public virtual tb_paymentRecord tb_paymentRecord2 { get; set; }
    }
}
