//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rpt_evaluate_h
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_rpt_evaluate_h()
        {
            this.tb_rpt_evaluate_d = new HashSet<tb_rpt_evaluate_d>();
        }
    
        public int evaluateId { get; set; }
        public Nullable<int> evaluateNo { get; set; }
        public Nullable<int> evaluateYear { get; set; }
        public string evaluateDue { get; set; }
        public Nullable<System.DateTime> evaluateDate { get; set; }
        public string evaluateForm { get; set; }
        public string empNo { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> hireDate { get; set; }
        public string workingDue { get; set; }
        public string positionName { get; set; }
        public string dept { get; set; }
        public string companyName { get; set; }
        public string mgrName { get; set; }
        public string mgr2Name { get; set; }
        public string ownerComment { get; set; }
        public string managerscore1_Comment { get; set; }
        public string managerscore2_Comment { get; set; }
        public string managerscore3_Comment { get; set; }
        public string hrscore_Comment { get; set; }
        public Nullable<int> mgr1_increanPercent { get; set; }
        public Nullable<int> mgr1_increanLevel { get; set; }
        public Nullable<int> mgr1_increanPosition { get; set; }
        public string mgr1_comment { get; set; }
        public Nullable<int> mgr2_increanPercent { get; set; }
        public Nullable<int> mgr2_increanLevel { get; set; }
        public Nullable<int> mgr2_increanPosition { get; set; }
        public string mgr2_comment { get; set; }
        public Nullable<int> mgr3_increanPercent { get; set; }
        public Nullable<int> mgr3_increanLevel { get; set; }
        public Nullable<int> mgr3_increanPosition { get; set; }
        public string mgr3_comment { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_rpt_evaluate_d> tb_rpt_evaluate_d { get; set; }
    }
}
