//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rpt_evaluate_d
    {
        public int detailId { get; set; }
        public Nullable<int> evaluateId { get; set; }
        public Nullable<int> questionNumber { get; set; }
        public string questionName { get; set; }
        public Nullable<int> masterScore { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<double> managerscore1 { get; set; }
        public Nullable<double> managerscore2 { get; set; }
        public Nullable<double> managerscore3 { get; set; }
        public Nullable<double> hrscore { get; set; }
        public Nullable<double> lastScore { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_rpt_evaluate_h tb_rpt_evaluate_h { get; set; }
    }
}
