//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shift
    {
        public int shiftID { get; set; }
        public string shiftNo { get; set; }
        public Nullable<double> shiftPercent { get; set; }
        public Nullable<int> LastDay { get; set; }
    }
}
