//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SPRetirement
    {
        public int sprgID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<double> ltc_balance { get; set; }
        public Nullable<double> acc_balance { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> totalBalance { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
