//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_summary_pension
    {
        public int pension_ID { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string empWorkDayID { get; set; }
        public string deptCode { get; set; }
        public string sec { get; set; }
        public double pensionAmount_00 { get; set; }
        public double pensionAmount_01 { get; set; }
        public double pensionAmount_02 { get; set; }
        public double pensionAmount_03 { get; set; }
        public double pensionAmount_04 { get; set; }
        public double pensionAmount_05 { get; set; }
        public double pensionAmount_06 { get; set; }
        public double pensionAmount_07 { get; set; }
        public double pensionAmount_08 { get; set; }
        public double pensionAmount_09 { get; set; }
        public double pensionAmount_10 { get; set; }
        public double pensionAmount_11 { get; set; }
        public double pensionAmount_12 { get; set; }
        public int cal { get; set; }
    }
}
