//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_shiftWorking
    {
        public int shiftWorkingID { get; set; }
        public string shiftName { get; set; }
        public bool mo { get; set; }
        public System.TimeSpan mo_timeIn { get; set; }
        public System.TimeSpan mo_timeOut { get; set; }
        public bool tu { get; set; }
        public System.TimeSpan tu_timeIn { get; set; }
        public System.TimeSpan tu_timeOut { get; set; }
        public bool we { get; set; }
        public System.TimeSpan we_timeIn { get; set; }
        public System.TimeSpan we_timeOut { get; set; }
        public bool th { get; set; }
        public System.TimeSpan th_timeIn { get; set; }
        public System.TimeSpan th_timeOut { get; set; }
        public bool fr { get; set; }
        public System.TimeSpan fr_timeIn { get; set; }
        public System.TimeSpan fr_timeOut { get; set; }
        public bool sa { get; set; }
        public System.TimeSpan sa_timeIn { get; set; }
        public System.TimeSpan sa_timeOut { get; set; }
        public bool su { get; set; }
        public System.TimeSpan su_timeIn { get; set; }
        public System.TimeSpan su_timeOut { get; set; }
        public int dayAverage { get; set; }
        public string remark { get; set; }
        public Nullable<int> strDay { get; set; }
        public Nullable<int> endDay { get; set; }
        public Nullable<int> othour { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
