//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SLDRT_loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_SLDRT_loan()
        {
            this.tb_SLDRT_loanApprove = new HashSet<tb_SLDRT_loanApprove>();
            this.tb_SLDRT_loanDetail = new HashSet<tb_SLDRT_loanDetail>();
        }
    
        public int SLDRT_loanID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<double> amountLoan { get; set; }
        public Nullable<int> loanMonth { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public Nullable<double> loanPercent { get; set; }
        public Nullable<double> totalLoan { get; set; }
        public Nullable<System.DateTime> loanStart { get; set; }
        public Nullable<System.DateTime> loanEnd { get; set; }
        public string LoanReason { get; set; }
        public string loanFile { get; set; }
        public Nullable<double> payMonth { get; set; }
        public Nullable<int> paidStatus { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SLDRT_loanApprove> tb_SLDRT_loanApprove { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SLDRT_loanDetail> tb_SLDRT_loanDetail { get; set; }
    }
}
