//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_P_Userlevels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_P_Userlevels()
        {
            this.tbl_P_employeeLevel_GroupLevels = new HashSet<tbl_P_employeeLevel_GroupLevels>();
        }
    
        public int PUSLID { get; set; }
        public string Levelsname { get; set; }
        public Nullable<int> Levels { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string Rec_Type { get; set; }
        public string moreinfo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_P_employeeLevel_GroupLevels> tbl_P_employeeLevel_GroupLevels { get; set; }
    }
}
