//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_commentUpdateIncome
    {
        public int CUDID { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> empid { get; set; }
        public Nullable<bool> updateincome_percent { get; set; }
        public Nullable<bool> updateincomeLevels { get; set; }
        public Nullable<bool> updatePosition { get; set; }
        public string commentsbymanager { get; set; }
        public string commentsbyHR { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<int> hrid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string rectype { get; set; }
    }
}
