//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class test
    {
        public int empID { get; set; }
        public string empNo { get; set; }
        public string empDayID { get; set; }
        public string empTitleName { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string nickName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string nickName2 { get; set; }
        public Nullable<int> genderID { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> fstatusID { get; set; }
        public Nullable<int> nationalityID { get; set; }
        public Nullable<int> ethnicID { get; set; }
        public Nullable<int> religionID { get; set; }
        public string IDCrad { get; set; }
        public string passport { get; set; }
        public string address1 { get; set; }
        public Nullable<int> district_id1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> district_id2 { get; set; }
        public string empMobile { get; set; }
        public string empEmail { get; set; }
        public string empPhoto { get; set; }
        public Nullable<double> paymentPercent { get; set; }
        public string spName { get; set; }
        public string spMobile { get; set; }
        public string spEmail { get; set; }
        public string spAddress { get; set; }
        public string spJob { get; set; }
        public string spJobAddress { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> approveby { get; set; }
        public Nullable<int> pr_group { get; set; }
        public Nullable<int> prApproval { get; set; }
        public Nullable<int> prApproval_hr { get; set; }
        public Nullable<int> prApproval_mgr1 { get; set; }
        public Nullable<int> prApproval_mgr2 { get; set; }
        public Nullable<int> prApproval_mgr3 { get; set; }
        public Nullable<int> rqApproval1 { get; set; }
        public Nullable<int> rqApproval2 { get; set; }
        public Nullable<int> rqApproval3 { get; set; }
        public Nullable<int> rqApproval_org1 { get; set; }
        public Nullable<int> rqApproval_org2 { get; set; }
        public Nullable<int> rqApproval_org3 { get; set; }
    }
}
