//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_empMgr
    {
        public int tmp_id { get; set; }
        public Nullable<int> empID { get; set; }
        public string empFullName { get; set; }
        public Nullable<int> user_add { get; set; }
    }
}
