//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_loan
    {
        public int tmp_loanID { get; set; }
        public Nullable<int> loanID { get; set; }
        public Nullable<double> amountLoan { get; set; }
        public Nullable<int> cals { get; set; }
    }
}
