//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_shiftWorkingDay
    {
        public int tmp_id { get; set; }
        public Nullable<int> shiftWorkingID { get; set; }
        public Nullable<int> sumWorkingDay { get; set; }
        public Nullable<int> publicHoliday { get; set; }
        public string ipaddress { get; set; }
        public Nullable<int> cal { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
