//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_rpt1006
    {
        public int tmp_id { get; set; }
        public string transactionNo { get; set; }
        public string deptGroupCode { get; set; }
        public string deptGroupName { get; set; }
        public Nullable<double> staffCount { get; set; }
        public string deptName { get; set; }
        public string deptCode { get; set; }
        public Nullable<double> grossSalaryBenefits { get; set; }
        public Nullable<double> advanceBonus { get; set; }
        public Nullable<double> deductEmpSSO { get; set; }
        public Nullable<double> deductTaxs { get; set; }
        public Nullable<double> netIncome { get; set; }
        public Nullable<double> loan_phone_FHF { get; set; }
        public Nullable<double> sldrtFund { get; set; }
        public Nullable<double> canteenOther { get; set; }
        public Nullable<double> leaveingPackage { get; set; }
        public Nullable<double> netToPay { get; set; }
        public Nullable<double> employerSSO { get; set; }
        public Nullable<double> netToPayfromMasterData { get; set; }
        public Nullable<double> variance { get; set; }
        public string remark { get; set; }
        public Nullable<int> viewsheet { get; set; }
        public Nullable<int> topic { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> yearCal { get; set; }
        public Nullable<int> ssoExpert { get; set; }
    }
}
