//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_notiMenu
    {
        public int tempId { get; set; }
        public Nullable<int> mgrId { get; set; }
        public Nullable<int> leave { get; set; }
        public Nullable<int> wff { get; set; }
        public Nullable<int> wfh { get; set; }
        public Nullable<int> ot { get; set; }
        public Nullable<int> deleagte { get; set; }
        public Nullable<int> totalleave { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> countsalaryapprove { get; set; }
        public Nullable<int> deleagte_rq { get; set; }
    }
}
