//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_checkworkday
    {
        public int tmp_id { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public string fullNameLA { get; set; }
        public string fullNameEN { get; set; }
        public Nullable<System.DateTime> workDay { get; set; }
        public Nullable<int> workMonth { get; set; }
        public Nullable<int> workYear { get; set; }
        public Nullable<double> shift1_n { get; set; }
        public Nullable<double> shift1_ot { get; set; }
        public Nullable<double> shift1_wd_total { get; set; }
        public Nullable<double> shift1_ot_total { get; set; }
        public Nullable<double> shift2_n { get; set; }
        public Nullable<double> shift2_ot { get; set; }
        public Nullable<double> shift2_wd_sun { get; set; }
        public Nullable<double> shift2_ot_sun { get; set; }
        public Nullable<double> shift2_wd_total { get; set; }
        public Nullable<double> shift2_ot_total { get; set; }
        public Nullable<double> total_wd { get; set; }
        public Nullable<double> total_ot { get; set; }
        public Nullable<double> leave1 { get; set; }
        public Nullable<double> leave2 { get; set; }
        public Nullable<double> leave3 { get; set; }
        public Nullable<double> leave4 { get; set; }
        public Nullable<double> sys_leave { get; set; }
        public Nullable<double> sys_OTh { get; set; }
        public Nullable<double> sys_OTh1 { get; set; }
        public Nullable<double> sys_OTh2 { get; set; }
        public Nullable<double> sys_OTh3 { get; set; }
        public Nullable<double> sys_OTh4 { get; set; }
        public Nullable<int> status_id { get; set; }
        public string statusText { get; set; }
        public Nullable<double> dayoff { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> mrgID { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
