//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_advBonus
    {
        public string transactionno { get; set; }
        public Nullable<int> empid { get; set; }
        public string empno { get; set; }
        public string firstname1 { get; set; }
        public string lastname1 { get; set; }
        public string firstname2 { get; set; }
        public string lastname2 { get; set; }
        public string sec { get; set; }
        public string gendertext { get; set; }
        public double basicsalary { get; set; }
        public int bonusmonth { get; set; }
        public int bonusyear { get; set; }
        public string ltlhiredate { get; set; }
        public string bonusStrdate { get; set; }
        public string bonusDate { get; set; }
        public string bonusEnddate { get; set; }
        public int nummonthbonus { get; set; }
        public decimal lengthservice { get; set; }
        public double bonusamount { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> typeid { get; set; }
    }
}
