//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_approved
    {
        public int leaveApproveID { get; set; }
        public string leaveApproveNo { get; set; }
        public int leaveRequestID { get; set; }
        public string noted { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public int empID { get; set; }
        public string empNo { get; set; }
        public string leaveType { get; set; }
        public int Expr1 { get; set; }
        public string leaveRequestNo { get; set; }
    }
}
