//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_dept_unit_employee
    {
        public int deptID { get; set; }
        public Nullable<int> companyID { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string unitName1 { get; set; }
        public int empID { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string nickName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string nickName2 { get; set; }
        public int unitID { get; set; }
        public string deptName2 { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> mgrid { get; set; }
        public string empNo { get; set; }
        public string empPosition { get; set; }
    }
}
