//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emp_question_by_group
    {
        public int empID { get; set; }
        public string QName { get; set; }
        public Nullable<double> scores { get; set; }
        public Nullable<int> pr_group { get; set; }
    }
}
