//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empPaymentRecord
    {
        public int salaryID { get; set; }
        public Nullable<int> empID { get; set; }
        public string empTitleName { get; set; }
        public string empEmail { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> YearCal { get; set; }
        public Nullable<double> EmpWorkingDay { get; set; }
        public string empPosition { get; set; }
        public string strDate { get; set; }
        public string endDate { get; set; }
        public Nullable<System.DateTime> nStrDate { get; set; }
        public Nullable<System.DateTime> nEnddate { get; set; }
        public int deptID { get; set; }
        public double deductTaxs { get; set; }
        public string empNo { get; set; }
        public string empDayID { get; set; }
        public string empType { get; set; }
        public string grossSalaryBenefits { get; set; }
        public string endDateYM { get; set; }
        public string deptGroupCode { get; set; }
        public string deptGroupName { get; set; }
        public string Yearmonthly { get; set; }
    }
}
