//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employess
    {
        public int empID { get; set; }
        public string empNo { get; set; }
        public string empTitleName { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string nickName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string nickName2 { get; set; }
        public Nullable<int> genderID { get; set; }
        public string genderText { get; set; }
        public string dob { get; set; }
        public Nullable<int> fstatusID { get; set; }
        public string fstatusText { get; set; }
        public Nullable<int> nationalityID { get; set; }
        public string nationalityText { get; set; }
        public Nullable<int> ethnicID { get; set; }
        public string ethnicName1 { get; set; }
        public string ethnicName2 { get; set; }
        public string IDCrad { get; set; }
        public string passport { get; set; }
        public string empMobile { get; set; }
        public string empEmail { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public Nullable<int> status_id { get; set; }
        public string assignmentLocation { get; set; }
        public string currentAddress { get; set; }
        public Nullable<int> costCenterID { get; set; }
        public string costCenterCode { get; set; }
        public string costCenterText { get; set; }
        public string empPosition { get; set; }
        public Nullable<int> unitID { get; set; }
        public Nullable<int> empLevelID { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public Nullable<int> empGroupID { get; set; }
        public Nullable<int> shiftWorkingID { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> deptID { get; set; }
        public Nullable<int> religionID { get; set; }
        public string address1 { get; set; }
        public Nullable<int> district_id1 { get; set; }
        public Nullable<int> Pro_ID { get; set; }
        public string empPhoto { get; set; }
        public Nullable<double> paymentPercent { get; set; }
        public string spName { get; set; }
        public string spMobile { get; set; }
        public string spEmail { get; set; }
        public string spAddress { get; set; }
        public string spJob { get; set; }
        public string spJobAddress { get; set; }
        public Nullable<int> workingStatusID { get; set; }
        public Nullable<int> empTypeID { get; set; }
        public Nullable<int> empInfoID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<System.DateTime> actingDate { get; set; }
        public string companyCode { get; set; }
        public string companyName1 { get; set; }
        public string companyName2 { get; set; }
        public string empDayID { get; set; }
        public Nullable<int> positionID { get; set; }
        public System.DateTime dob1 { get; set; }
        public Nullable<int> ssoExpert { get; set; }
        public Nullable<int> approveby { get; set; }
        public Nullable<int> pr_group { get; set; }
        public Nullable<int> prApproval { get; set; }
        public string empLevelName1 { get; set; }
        public Nullable<int> pr_groupID { get; set; }
    }
}
