//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empleaverequestall
    {
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public int unitID { get; set; }
        public string empNo { get; set; }
        public Nullable<int> mgrid { get; set; }
        public int empID { get; set; }
        public string yearleave { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string returndate { get; set; }
        public string leaveTypeCode { get; set; }
        public string leaveTypeName1 { get; set; }
        public string leaveTypeName2 { get; set; }
        public double amountdayleave { get; set; }
    }
}
