//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_evaluate_header
    {
        public int HDQID { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string rec_type { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<double> kpi_percent { get; set; }
        public Nullable<double> kbi_percent { get; set; }
        public Nullable<int> GLUID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> empId { get; set; }
        public Nullable<int> ownerscore_StatusId { get; set; }
        public Nullable<int> managerscore1_statusId { get; set; }
        public Nullable<int> managerscore2_statusId { get; set; }
        public Nullable<int> managerscore3_statusId { get; set; }
        public Nullable<int> hrscore_statusid { get; set; }
        public Nullable<int> hrId { get; set; }
        public Nullable<int> mgr1_id { get; set; }
        public Nullable<int> mgr2_id { get; set; }
        public Nullable<int> mgr3_id { get; set; }
        public Nullable<int> headerNo { get; set; }
        public Nullable<int> headerYear { get; set; }
    }
}
