//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_leaveBalanceAll
    {
        public int leaveRequestID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> leaveTypeID { get; set; }
        public Nullable<double> leaveDay { get; set; }
        public Nullable<double> TotalDay { get; set; }
        public string leaveTypeName1 { get; set; }
        public string leaveTypeName2 { get; set; }
    }
}
