//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_leaverequest
    {
        public int leaveRequestID { get; set; }
        public string leaveRequestNo { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> leaveTypeID { get; set; }
        public string leaveDay { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<double> amountDay { get; set; }
        public string noted { get; set; }
        public Nullable<int> delegateEmpID { get; set; }
        public string imagePath { get; set; }
        public string fileAttached { get; set; }
        public string fileType { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<int> transactionType { get; set; }
        public Nullable<System.DateTime> expDate { get; set; }
        public string referAdd { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> from_device { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> startyear { get; set; }
    }
}
