//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_leaverequestalldetails_2
    {
        public int leaverequestid { get; set; }
        public string leaverequestno { get; set; }
        public Nullable<int> empid { get; set; }
        public string firstname1 { get; set; }
        public string firstname2 { get; set; }
        public string lastname1 { get; set; }
        public string lastname2 { get; set; }
        public Nullable<int> leavetypeid { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.DateTime> returndate { get; set; }
        public Nullable<double> amountday { get; set; }
        public string noted { get; set; }
        public Nullable<int> delegateEmpID { get; set; }
        public string fileAttached { get; set; }
        public Nullable<int> managerID { get; set; }
        public int transactiontype { get; set; }
        public string transactiontypetext { get; set; }
        public System.DateTime expdate { get; set; }
        public string referadd { get; set; }
        public Nullable<int> status_ID { get; set; }
        public string imagepath { get; set; }
        public string status_text { get; set; }
        public string delegate_fname1 { get; set; }
        public string delegate_fname2 { get; set; }
        public string delegate_lname1 { get; set; }
        public string delegate_lname2 { get; set; }
        public string manager_fname1 { get; set; }
        public string manager_fname2 { get; set; }
        public string manager_lastname1 { get; set; }
        public string manager_lastname2 { get; set; }
        public string empNo { get; set; }
        public string leaveDay { get; set; }
        public string leaveTypeName1 { get; set; }
        public string leaveTypeName2 { get; set; }
        public string leavemorning { get; set; }
        public string leaveafternoon { get; set; }
        public Nullable<System.DateTime> lastApproveDate { get; set; }
    }
}
