//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_paymentYearmonth
    {
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string yearmonth { get; set; }
        public int salaryID { get; set; }
    }
}
