//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_paymentRecord
    {
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string costCenterCode { get; set; }
        public string costCenterText { get; set; }
        public string unitCode { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public Nullable<int> empID { get; set; }
        public string empNo { get; set; }
        public Nullable<double> grossSalaryBenefits { get; set; }
        public Nullable<double> advanceBonus { get; set; }
        public Nullable<double> deductEmpSSO { get; set; }
        public Nullable<double> deductTaxs { get; set; }
        public Nullable<double> grossIncome { get; set; }
        public Nullable<double> deductFHFdeductOther { get; set; }
        public Nullable<double> deduct_SLDRT_fun { get; set; }
        public Nullable<double> canteenNET { get; set; }
        public Nullable<double> severanceBook { get; set; }
        public Nullable<double> NetToPay { get; set; }
        public Nullable<double> employerSSO { get; set; }
        public Nullable<int> NetToPaymaster { get; set; }
        public Nullable<double> Variance { get; set; }
        public string remark { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> YearCal { get; set; }
        public string bankName { get; set; }
        public int salaryID { get; set; }
    }
}
