//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_reportOTDetailsbyEmp
    {
        public Nullable<int> empID { get; set; }
        public int otRequestID { get; set; }
        public string otRequestNo { get; set; }
        public string otSettingType { get; set; }
        public string startdate { get; set; }
        public Nullable<System.DateTime> stdatenoformat { get; set; }
        public System.TimeSpan startTime { get; set; }
        public System.TimeSpan endTime { get; set; }
        public double qtyHour { get; set; }
        public Nullable<double> otSettingValues { get; set; }
        public string rateCode { get; set; }
        public string noted { get; set; }
        public string otTypeText { get; set; }
        public string createdatetime { get; set; }
    }
}
