//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_rpt1013_only2person
    {
        public string ssonumber { get; set; }
        public string empno { get; set; }
        public string empName { get; set; }
        public string salary { get; set; }
        public string ssosalary { get; set; }
        public string employeesso { get; set; }
        public string employersso { get; set; }
    }
}
