//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_selEmpHeader
    {
        public Nullable<int> HDQID { get; set; }
        public Nullable<int> empId { get; set; }
        public string empNo { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string unitName1 { get; set; }
        public string deptName1 { get; set; }
        public string empTitleName { get; set; }
        public string empPosition { get; set; }
        public string companyName1 { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public Nullable<int> pr_group { get; set; }
        public Nullable<int> mgr1_id { get; set; }
        public Nullable<int> mgr2_id { get; set; }
        public Nullable<int> mgr3_id { get; set; }
        public Nullable<int> hrId { get; set; }
    }
}
