//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_unit
    {
        public int unitID { get; set; }
        public string unitCode { get; set; }
        public int deptID { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> parentID { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public string p1 { get; set; }
        public string p2 { get; set; }
        public string pcode { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
