//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_user_permission
    {
        public int userID { get; set; }
        public Nullable<int> empID { get; set; }
        public string appTokenKey { get; set; }
        public string webTokenKey { get; set; }
        public string Device_token { get; set; }
        public int roleId { get; set; }
        public string roleName { get; set; }
        public int appId { get; set; }
        public Nullable<int> app_permissionId { get; set; }
        public Nullable<int> app_view { get; set; }
        public Nullable<int> app_add { get; set; }
        public Nullable<int> app_edit { get; set; }
        public Nullable<int> app_action { get; set; }
        public Nullable<int> app_del { get; set; }
    }
}
