//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_users
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> expDate { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string nickName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string nickName2 { get; set; }
        public string genderText { get; set; }
        public string roleName { get; set; }
        public string appTokenKey { get; set; }
        public string webTokenKey { get; set; }
        public string Device_token { get; set; }
        public Nullable<int> sendNoti { get; set; }
        public string empEmail { get; set; }
        public string empNo { get; set; }
        public string empTitleName { get; set; }
        public Nullable<int> unitID { get; set; }
        public string unitCode { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public Nullable<int> parentID { get; set; }
        public int deptID { get; set; }
        public string deptCode { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public int companyID { get; set; }
        public string companyCode { get; set; }
        public string companyName1 { get; set; }
        public string companyName2 { get; set; }
        public string companyPhone { get; set; }
        public string companyFax { get; set; }
        public string companyWebsite { get; set; }
        public string companyFaebook { get; set; }
        public string empMobile { get; set; }
        public string empPhoto { get; set; }
        public Nullable<int> langID { get; set; }
        public Nullable<int> mgrid { get; set; }
        public int workingStatusID { get; set; }
        public string workingStatusText { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public string empPosition { get; set; }
        public Nullable<int> workingyear { get; set; }
        public Nullable<int> pr_group { get; set; }
        public Nullable<int> prApproval { get; set; }
    }
}
