//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_questionlistdetails
    {
        public int qtlid { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> qtid { get; set; }
        public Nullable<int> qno { get; set; }
        public string qname { get; set; }
        public string rec_type { get; set; }
        public string createdates { get; set; }
        public string headername { get; set; }
        public string fstartdates { get; set; }
        public string fenddate { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<int> questoinpartno { get; set; }
        public string questionpartname { get; set; }
        public string questiontypename { get; set; }
        public double scorelistdetails { get; set; }
    }
}
