//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_commentquestionpartbyDirector
    {
        public int CDQID { get; set; }
        public Nullable<int> QTID { get; set; }
        public Nullable<int> Commentby { get; set; }
        public Nullable<int> CommentTo { get; set; }
        public string Textcomment { get; set; }
        public Nullable<int> QuestoinpartNo { get; set; }
        public string Questionpartname { get; set; }
        public Nullable<double> score { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string RecType { get; set; }
        public string laoname { get; set; }
        public Nullable<int> hdqid { get; set; }
    }
}
