//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_employeelevel_grouplevels
    {
        public int pegeid { get; set; }
        public Nullable<int> puslid { get; set; }
        public Nullable<int> gluid { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string groupname { get; set; }
        public Nullable<int> grouplevels { get; set; }
        public string levelsname { get; set; }
        public Nullable<int> levels { get; set; }
        public string pgcreatedate { get; set; }
        public Nullable<int> createby { get; set; }
        public string emp_nbr { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string titlename { get; set; }
        public string departname { get; set; }
        public string unitname { get; set; }
        public string workstatus { get; set; }
    }
}
