//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_listquestionempdetails
    {
        public int LQDID { get; set; }
        public Nullable<int> QTLID { get; set; }
        public int HDQID { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<double> managerscore { get; set; }
        public Nullable<double> hrscore { get; set; }
        public Nullable<int> mgrid { get; set; }
        public string ownercreatedate { get; set; }
        public Nullable<int> Qno { get; set; }
        public string QName { get; set; }
        public string headername { get; set; }
        public string Emp_nbr { get; set; }
        public string User_email { get; set; }
        public string name { get; set; }
        public string engname { get; set; }
        public string rec_type_emp { get; set; }
        public string rec_type_mgr { get; set; }
        public string rec_type_hr { get; set; }
    }
}
