//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_questionpart
    {
        public int QTID { get; set; }
        public Nullable<int> TQID { get; set; }
        public Nullable<int> QuestoinpartNo { get; set; }
        public string Questionpartname { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string rec_type { get; set; }
        public string questionnametype { get; set; }
        public double score { get; set; }
        public Nullable<int> hdqid { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string headerstatus { get; set; }
    }
}
