//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_headerquestionemployeescoresummary
    {
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string user_email { get; set; }
        public string emp_nbr { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string titlename { get; set; }
        public string Departname { get; set; }
        public string cmname { get; set; }
        public string workstatus { get; set; }
        public Nullable<int> empscore { get; set; }
        public int ownerscore { get; set; }
        public Nullable<int> totalempscore { get; set; }
        public Nullable<int> mgrscore { get; set; }
        public int mgrownerscore { get; set; }
        public Nullable<int> totalmgrscore { get; set; }
        public double hrscore { get; set; }
        public double hrownerscore { get; set; }
        public Nullable<double> totalhrscore { get; set; }
        public Nullable<int> totalquestion { get; set; }
        public Nullable<int> totalownerquestion { get; set; }
        public Nullable<int> totalhrquestion { get; set; }
        public string comparesocre_grade { get; set; }
        public string comparescore_info { get; set; }
        public string headername { get; set; }
        public string headerstartdate { get; set; }
        public string headerenddate { get; set; }
    }
}
