//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_headerquestiongrouplevel
    {
        public int HQGID { get; set; }
        public Nullable<int> HDQID { get; set; }
        public Nullable<int> GLUID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> GroupLevels { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string headerquestionType { get; set; }
    }
}
