//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_app_noti
    {
        public int notiID { get; set; }
        public Nullable<int> empID { get; set; }
        public string Device_token { get; set; }
        public string noti_sound { get; set; }
        public string Noti_title { get; set; }
        public string Noti_body { get; set; }
        public string Noti_link { get; set; }
        public string noti_click_ation { get; set; }
        public string noti_status { get; set; }
        public string noti_screen { get; set; }
        public string noti_message { get; set; }
        public string noti_ids { get; set; }
        public string sendFrom { get; set; }
        public Nullable<System.DateTime> date_send { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string statusText { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string empNo { get; set; }
    }
}
