//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_leaveNotApproved
    {
        public string empNo { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<double> amountDay { get; set; }
        public string leaveTypeName1 { get; set; }
        public int leaveRequestID { get; set; }
        public Nullable<int> status_ID { get; set; }
    }
}
