//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_empDob
    {
        public int empID { get; set; }
        public string empNo { get; set; }
        public string empEmail { get; set; }
        public string empTitleName { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string genderText { get; set; }
        public string unitName1 { get; set; }
        public string unitName2 { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string empPosition { get; set; }
        public string companyname1 { get; set; }
        public string companyname2 { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> ages { get; set; }
    }
}
