//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_listquestionbyemployeegenerate
    {
        public int lqdid { get; set; }
        public Nullable<int> qtlid { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<double> ownerscore { get; set; }
        public Nullable<System.DateTime> ownercreate { get; set; }
        public Nullable<int> mgrid { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_nbr { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
        public string user_email { get; set; }
        public string cmname { get; set; }
        public string unitname { get; set; }
        public string departname { get; set; }
        public string titlename { get; set; }
        public string rec_type_emp { get; set; }
        public string rec_type_mgr { get; set; }
        public string rec_type_hr { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    }
}
