//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_users
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> roleID { get; set; }
        public string appTokenKey { get; set; }
        public string webTokenKey { get; set; }
        public string Device_token { get; set; }
        public Nullable<int> sendNoti { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> strDate { get; set; }
        public Nullable<System.DateTime> expDate { get; set; }
        public Nullable<System.DateTime> expSession { get; set; }
        public Nullable<int> langID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> resetCode { get; set; }
        public Nullable<int> nextChange { get; set; }
    
        public virtual tb_app_role tb_app_role { get; set; }
        public virtual tb_employees tb_employees { get; set; }
    }
}
