//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_checkInOut
    {
        public int chechID { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<System.DateTime> checkTime { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string checkInOut { get; set; }
        public Nullable<int> status_id { get; set; }
        public byte[] picture { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
