//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_spouse
    {
        public int spouseID { get; set; }
        public Nullable<int> empID { get; set; }
        public string sName { get; set; }
        public string sMobile { get; set; }
        public string sEmail { get; set; }
        public string sAddress { get; set; }
        public string sJob { get; set; }
        public string jobAddress { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
