//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_salary_list
    {
        public int salaryID { get; set; }
        public System.DateTime salaryDate { get; set; }
        public int salaryMonth { get; set; }
        public int salaryYear { get; set; }
        public string generateDate { get; set; }
        public Nullable<int> ownerID { get; set; }
        public string ApproveDate { get; set; }
        public Nullable<int> mgrID { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_id { get; set; }
        public string statusText { get; set; }
        public Nullable<int> fingerUpload { get; set; }
        public Nullable<int> approveFinger { get; set; }
        public Nullable<int> leaveDay { get; set; }
        public Nullable<int> oth { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string mgrF1 { get; set; }
        public string mgrL1 { get; set; }
        public string mgrF2 { get; set; }
        public string mgrL2 { get; set; }
        public string transactionNo { get; set; }
        public Nullable<int> workingDay { get; set; }
        public Nullable<int> additionalPayment { get; set; }
        public Nullable<int> saleIncentive { get; set; }
        public Nullable<int> deductFHF { get; set; }
        public Nullable<int> deductOther { get; set; }
        public Nullable<int> personalLoan { get; set; }
        public Nullable<int> SLDRT { get; set; }
        public Nullable<int> approveWorking { get; set; }
        public Nullable<int> cycleRun { get; set; }
        public Nullable<int> reportPrint { get; set; }
        public Nullable<int> processStatus { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> reportGen { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
    }
}
