//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_rpt1011
    {
        public int tmpid { get; set; }
        public string transactionNo { get; set; }
        public string deptGroupCode { get; set; }
        public string deptGroupName { get; set; }
        public string costCenter { get; set; }
        public string unitName { get; set; }
        public Nullable<int> total_active { get; set; }
        public Nullable<int> permanent_active { get; set; }
        public Nullable<int> fixed_perary_active { get; set; }
        public Nullable<int> permanaent_NoActive { get; set; }
        public string groupInHCR { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> monthCal { get; set; }
        public Nullable<int> yearCal { get; set; }
    }
}
