//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_emp_ot
    {
        public int otRequestID { get; set; }
        public string otRequestNo { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> otTypeID { get; set; }
        public string otTypeText { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<System.TimeSpan> otStartTime { get; set; }
        public Nullable<System.TimeSpan> otEndTime { get; set; }
        public string noted { get; set; }
        public string fileAttached { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> otSettingID { get; set; }
        public Nullable<System.TimeSpan> startTime { get; set; }
        public Nullable<System.TimeSpan> endTime { get; set; }
        public Nullable<double> qtyHour { get; set; }
        public Nullable<int> minusHour { get; set; }
        public Nullable<double> otSettingValues { get; set; }
        public Nullable<double> payment { get; set; }
    }
}
