//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_headerquestionemployeefinishedgroup
    {
        public Nullable<int> Emp_id { get; set; }
        public string Emp_nbr { get; set; }
        public string User_email { get; set; }
        public string name { get; set; }
        public string engname { get; set; }
        public string headername { get; set; }
        public Nullable<int> mgrid { get; set; }
        public string rec_type_emp { get; set; }
        public string rec_type_mgr { get; set; }
        public string rec_type_hr { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> directorapprove { get; set; }
        public string rec_type_director { get; set; }
        public string hrEmail { get; set; }
        public string laoname { get; set; }
        public string englishname { get; set; }
    }
}
