//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_leaveSetting
    {
        public int leaveSettingID { get; set; }
        public int leaveTypeID { get; set; }
        public int empGroupID { get; set; }
        public Nullable<int> amountDay { get; set; }
        public string remark { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_empGroup tb_empGroup { get; set; }
        public virtual tb_leaveType tb_leaveType { get; set; }
    }
}
