//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_company()
        {
            this.tb_department = new HashSet<tb_department>();
        }
    
        public int companyID { get; set; }
        public Nullable<int> groupId { get; set; }
        public string companyCode { get; set; }
        public string companyName1 { get; set; }
        public string companyName2 { get; set; }
        public string companyPhone { get; set; }
        public string companyFax { get; set; }
        public string companyWebsite { get; set; }
        public string companyFaebook { get; set; }
        public string companyLogo { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_department> tb_department { get; set; }
    }
}
