//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_employeeLeavedetails
    {
        public string leaveRequestNo { get; set; }
        public string empNo { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string empPosition { get; set; }
        public string deptName1 { get; set; }
        public string deptName2 { get; set; }
        public string leavestartdate { get; set; }
        public string leaveenddate { get; set; }
        public string returndate { get; set; }
        public Nullable<decimal> leaveDay { get; set; }
        public string leaveTypeName1 { get; set; }
        public string leaveTypeName2 { get; set; }
        public string noted { get; set; }
        public Nullable<System.DateTime> n_startdate { get; set; }
        public Nullable<System.DateTime> n_enddate { get; set; }
        public Nullable<System.DateTime> n_returndate { get; set; }
        public Nullable<int> companyID { get; set; }
        public Nullable<int> deptID { get; set; }
        public string textstatus { get; set; }
        public Nullable<int> managerID { get; set; }
        public Nullable<double> amountDay { get; set; }
        public int empID { get; set; }
        public string dob { get; set; }
        public string genderText { get; set; }
        public string fstatusText { get; set; }
        public string nationalityText { get; set; }
        public string ethnicName1 { get; set; }
        public string empMobile { get; set; }
        public string empEmail { get; set; }
        public Nullable<System.DateTime> hireDay { get; set; }
        public string companyName1 { get; set; }
    }
}
