//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_workingStatus
    {
        public int workingStatusID { get; set; }
        public string workingStatusText { get; set; }
        public Nullable<int> salaryCal { get; set; }
        public Nullable<int> status_id { get; set; }
    }
}
