//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_iBankName
    {
        public string bankName { get; set; }
        public string bankAccountName { get; set; }
        public string bankAccountNo { get; set; }
        public string endate { get; set; }
        public Nullable<double> TotalNetToPay { get; set; }
        public int id { get; set; }
    }
}
