//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_employees()
        {
            this.tb_advpay = new HashSet<tb_advpay>();
            this.tb_approvalSetting = new HashSet<tb_approvalSetting>();
            this.tb_delagate = new HashSet<tb_delagate>();
            this.tb_delegate_request = new HashSet<tb_delegate_request>();
            this.tb_emp_question = new HashSet<tb_emp_question>();
            this.tb_empAllowance = new HashSet<tb_empAllowance>();
            this.tb_empBankAccount = new HashSet<tb_empBankAccount>();
            this.tb_empDeduction = new HashSet<tb_empDeduction>();
            this.tb_empEducation = new HashSet<tb_empEducation>();
            this.tb_empFamily = new HashSet<tb_empFamily>();
            this.tb_empIncome = new HashSet<tb_empIncome>();
            this.tb_empInfo = new HashSet<tb_empInfo>();
            this.tbl_p_listquestionempdetails = new HashSet<tbl_p_listquestionempdetails>();
            this.tb_empSSO = new HashSet<tb_empSSO>();
            this.tb_fhf = new HashSet<tb_fhf>();
            this.tb_incentive = new HashSet<tb_incentive>();
            this.tb_leaveRequest = new HashSet<tb_leaveRequest>();
            this.tb_loan = new HashSet<tb_loan>();
            this.tb_paymentRecord = new HashSet<tb_paymentRecord>();
            this.tb_severance = new HashSet<tb_severance>();
            this.tb_SLDRT_loan = new HashSet<tb_SLDRT_loan>();
            this.tb_spouse = new HashSet<tb_spouse>();
            this.tb_SPRetirement = new HashSet<tb_SPRetirement>();
            this.tb_users = new HashSet<tb_users>();
            this.tb_workingDay = new HashSet<tb_workingDay>();
            this.tmp_checkworkday = new HashSet<tmp_checkworkday>();
        }
    
        public int empID { get; set; }
        public string empNo { get; set; }
        public string empDayID { get; set; }
        public string empTitleName { get; set; }
        public string firstName1 { get; set; }
        public string lastName1 { get; set; }
        public string nickName1 { get; set; }
        public string firstName2 { get; set; }
        public string lastName2 { get; set; }
        public string nickName2 { get; set; }
        public Nullable<int> genderID { get; set; }
        public System.DateTime dob { get; set; }
        public Nullable<int> fstatusID { get; set; }
        public Nullable<int> nationalityID { get; set; }
        public Nullable<int> ethnicID { get; set; }
        public Nullable<int> religionID { get; set; }
        public string IDCrad { get; set; }
        public string passport { get; set; }
        public string address1 { get; set; }
        public Nullable<int> district_id1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> district_id2 { get; set; }
        public string empMobile { get; set; }
        public string empEmail { get; set; }
        public string empPhoto { get; set; }
        public Nullable<double> paymentPercent { get; set; }
        public string spName { get; set; }
        public string spMobile { get; set; }
        public string spEmail { get; set; }
        public string spAddress { get; set; }
        public string spJob { get; set; }
        public string spJobAddress { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<int> approveby { get; set; }
        public Nullable<int> pr_group { get; set; }
        public Nullable<int> prApproval { get; set; }
        public Nullable<int> prApproval_hr { get; set; }
        public Nullable<int> prApproval_mgr1 { get; set; }
        public Nullable<int> prApproval_mgr2 { get; set; }
        public Nullable<int> prApproval_mgr3 { get; set; }
        public Nullable<int> rqApproval1 { get; set; }
        public Nullable<int> rqApproval2 { get; set; }
        public Nullable<int> rqApproval3 { get; set; }
        public Nullable<int> rqApproval_org1 { get; set; }
        public Nullable<int> rqApproval_org2 { get; set; }
        public Nullable<int> rqApproval_org3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_advpay> tb_advpay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_approvalSetting> tb_approvalSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_delagate> tb_delagate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_delegate_request> tb_delegate_request { get; set; }
        public virtual tb_district tb_district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_emp_question> tb_emp_question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empAllowance> tb_empAllowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empBankAccount> tb_empBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empDeduction> tb_empDeduction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empEducation> tb_empEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empFamily> tb_empFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empIncome> tb_empIncome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empInfo> tb_empInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_p_listquestionempdetails> tbl_p_listquestionempdetails { get; set; }
        public virtual tb_ethnic tb_ethnic { get; set; }
        public virtual tb_fstatus tb_fstatus { get; set; }
        public virtual tb_gender tb_gender { get; set; }
        public virtual tb_nationality tb_nationality { get; set; }
        public virtual tb_religion tb_religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_empSSO> tb_empSSO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_fhf> tb_fhf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_incentive> tb_incentive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_leaveRequest> tb_leaveRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_loan> tb_loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_paymentRecord> tb_paymentRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_severance> tb_severance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SLDRT_loan> tb_SLDRT_loan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_spouse> tb_spouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SPRetirement> tb_SPRetirement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_users> tb_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_workingDay> tb_workingDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tmp_checkworkday> tmp_checkworkday { get; set; }
    }
}
