//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_tax
    {
        public int tmp_taxID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<double> tax_b1 { get; set; }
        public Nullable<double> tax_b2 { get; set; }
        public Nullable<double> tax_b3 { get; set; }
        public Nullable<double> tax_b4 { get; set; }
        public Nullable<double> tax_b5 { get; set; }
        public Nullable<double> tax_b6 { get; set; }
        public Nullable<double> tax_ex { get; set; }
    }
}
