//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_empFamily
    {
        public int empFamilyID { get; set; }
        public Nullable<int> empID { get; set; }
        public string empFamilyRelationships { get; set; }
        public string empFamilyFullName { get; set; }
        public string empFamilyJob { get; set; }
        public string empFamilyJobAddr { get; set; }
        public string empFamilyAddr { get; set; }
        public string empFamilyTel { get; set; }
        public string empFamilyEmail { get; set; }
        public Nullable<int> status_ID { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    
        public virtual tb_employees tb_employees { get; set; }
    }
}
