//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    
    public partial class pd_displayNotiapprove1_Result
    {
        public Nullable<double> leave { get; set; }
        public Nullable<double> wff { get; set; }
        public Nullable<double> wfh { get; set; }
        public Nullable<double> ot { get; set; }
        public Nullable<double> deleagte { get; set; }
        public Nullable<double> totalleave { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> countsalaryapprove { get; set; }
    }
}
