//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_noti
    {
        public int notiID { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<int> app_permissionId { get; set; }
        public Nullable<int> CountItem { get; set; }
        public Nullable<int> userView { get; set; }
        public Nullable<int> OldValues { get; set; }
    }
}
