//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_p_headerquestionEmployeeScoreSummary
    {
        public int HESSID { get; set; }
        public Nullable<int> hdqid { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> empscore { get; set; }
        public Nullable<int> ownerscore { get; set; }
        public Nullable<int> mgrscore { get; set; }
        public Nullable<int> mgrownerscore { get; set; }
        public Nullable<double> hrscore { get; set; }
        public Nullable<double> hrownerscore { get; set; }
        public Nullable<int> totalquestion { get; set; }
        public Nullable<int> totalownerquestion { get; set; }
        public Nullable<double> comparescore_min { get; set; }
        public Nullable<double> comparescore_max { get; set; }
        public string comparescore_grade { get; set; }
        public string comparescore_info { get; set; }
        public string rec_type { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createby { get; set; }
    }
}
