//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_p_questionlistheaderquestionUpdate
    {
        public int hdqid { get; set; }
        public int qtlid { get; set; }
        public Nullable<int> partNo { get; set; }
        public string partname { get; set; }
        public Nullable<int> qno { get; set; }
        public string qname { get; set; }
        public string rec_type { get; set; }
        public string headername { get; set; }
        public Nullable<System.DateTime> headerquestionstart { get; set; }
        public Nullable<System.DateTime> headerquestionenddate { get; set; }
    }
}
