//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_salary_approve
    {
        public int approveID { get; set; }
        public Nullable<int> salaryID { get; set; }
        public Nullable<int> approveLevel { get; set; }
        public Nullable<int> approverID { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> approveDate { get; set; }
        public Nullable<int> appType { get; set; }
        public Nullable<int> user_add { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
    }
}
