//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_emp_approve
    {
        public int EAPID { get; set; }
        public string empnote { get; set; }
        public Nullable<int> approveby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> createby { get; set; }
        public string rec_type { get; set; }
    }
}
